import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      colors: {
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cbdaff",
        "surface-container-highest": "#dfe3e8",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3135",
        "on-error-container": "#93000a",
        "on-secondary-container": "#505f7f",
        "on-primary-container": "#dde5ff",
        "on-background": "#181c20",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4f688c",
        "error-container": "#ffdad6",
        "surface-container-high": "#e5e8ed",
        "primary": "#004ba6",
        "secondary-fixed": "#d8e2ff",
        "on-surface": "#181c20",
        "surface-tint": "#165abe",
        "background": "#f7f9fe",
        "surface-container": "#ebeef3",
        "on-primary-fixed": "#001a43",
        "tertiary": "#375073",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed-variant": "#004397",
        "tertiary-fixed": "#d4e3ff",
        "secondary-fixed-dim": "#b8c6eb",
        "outline-variant": "#c2c6d5",
        "error": "#ba1a1a",
        "surface": "#f7f9fe",
        "primary-container": "#2563c7",
        "on-secondary-fixed-variant": "#384765",
        "outline": "#737784",
        "surface-dim": "#d7dadf",
        "on-tertiary-container": "#dae7ff",
        "on-tertiary-fixed-variant": "#2e486a",
        "inverse-primary": "#aec6ff",
        "surface-bright": "#f7f9fe",
        "primary-fixed-dim": "#aec6ff",
        "surface-variant": "#dfe3e8",
        "on-surface-variant": "#424753",
        "tertiary-fixed-dim": "#aec8f1",
        "secondary": "#505e7e",
        "on-primary": "#ffffff",
        "surface-container-low": "#f1f4f9",
        "inverse-on-surface": "#eef1f6",
        "on-secondary-fixed": "#0b1b37",
        "on-tertiary-fixed": "#001c3a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
